### PR TITLE
Try to adjust for GStreamer

### LINKED ISSUE #11: Does not build due to missing `gstreamer-devel`-0.10
See https://github.com/sailfishos-applications/flowplayer/actions/runs/6326328597/job/17179658869#step:4:81

`gstreamer-devel` is not provided for SFOS 2.2.0, only `gstreamer1.0-devel` is, and the latter still is as of SFOS 3.2.1.

SFOS 2.2.1 still provides a `gstreamer` package, which is installed alongside the `gstreamer1.0` package by default.  SFOS 3.2.1 does not provide a `gstreamer` package any longer.

`gstreamer1.0` was enabled in SailfishOS 1.1.9 ([release notes](https://together.jolla.com/question/107685/release-notes-119-eineheminlampi/#107685-release-highlights), [changelog](https://together.jolla.com/question/107684/changelog-119-eineheminlampi/?sort=votes&page=1#107684-xulrunner-qt5)), the package itself must have been added earlier.

### Consequence
Need to migrate FlowPlayer to from `gstreamer` / `gstreamer-devel`-0.10 to `gstreamer1.0` / `gstreamer1.0-devel`.

### PR DESCRIPTION
**Pull request by dcaliste**
close #11 

Still not tested.

### CODE REVIEW

**Comment by dcaliste** [comment]
Quickly tested, songs are playing and seeking is working.

**Review by Olf0 — APPROVED** [review]
@dcaliste, thank you very much: This is looking excellent.

So I may also delete `src/taglib` and `src/mytaglib`, right?

**Comment by dcaliste** [comment]
Sorry @Olf0 , I was busy yesterday evening. Yes, I think the internal taglib can be removed, as you did. In case there are some modifications CepiPerez did for the purposes of FlowPlayer, they can still be recovered and added upstream, since `taglib` is present in Sailfish, it's easier. Of course, it means it's not compatible with Harbour, but this can also be treated separately by bundling the SailfishOS version inside the RPM if needed.

**Comment by Olf0** [comment]
> Of course, it means it's not compatible with Harbour, but this can also be treated separately by bundling the SailfishOS version inside the RPM if needed.

Oh, this is an aspect I missed (spontaneously I only thought of the intention to [replace the outdated `taglib-1.7.2` SailfishOS provided back then](https://github.com/sailfishos-applications/flowplayer/pull/22#issue-2026858917)) and this might have been another relevant reason, why [CepiPerez copied the source tree of `taglib-1.9.1`](https://github.com/sailfishos-applications/flowplayer/tree/0.1-9/src/taglib).

> In case there are some modifications CepiPerez did for the purposes of FlowPlayer, they can still be recovered and added upstream, …

I saw his own additions to `taglib` in [the `mytaglib` directory](https://github.com/sailfishos-applications/flowplayer/tree/0.1-9/src/mytaglib), which partially substitutes files of `taglib-1.9.1` but mostly adds new ones.  As I did not expect these changes to work with a vastly newer version (i.e. `taglib-1.11.1`), have no idea if CepiPerez was the original author of the files in the `mytaglib` directory and if any of these changes have already been upstreamed, I removed this directory ad hoc together with the `taglib` one and [the `lib` one](https://github.com/sailfishos-applications/flowplayer/tree/0.1-9/lib), which contains a precompiled DLL (`libmytaglib.so`: no idea why / what for).  In hindsight I may have been a little bit too "trigger happy" yesterday night, but as you stated, *"they can still be recovered"*.

I had the *impression* that the `taglib` here was the original `taglib-1.9.1` (i.e. unaltered), but did **not** carry out any proper checks (e.g. downloading and `diff`ing).

@CepiPerez, feel free to comment on my wild guesswork WRT `taglib` and `mytaglib`, or leave it, if you lack the time, motivation etc.

**Pull request merged**
